[[services]]
name = "server"
builder = "dockerfile"
dockerfilePath = "./server/Dockerfile"
startCommand = "node server/server.js"
port = 4000

[[services]]
name = "client"
builder = "dockerfile"
dockerfilePath = "./client/Dockerfile"
startCommand = "nginx -g 'daemon off;'"
port = 80

[[services]]
name = "worker"
builder = "dockerfile"
dockerfilePath = "./feedback-pipeline/Dockerfile"
startCommand = "node feedback-pipeline/worker.js"
port = 3006

[[services]]
name = "api"
builder = "dockerfile"
dockerfilePath = "./feedback-pipeline/Dockerfile"
startCommand = "node feedback-pipeline/api-server.js"
port = 3005
